version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_gin_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - CONFIG_PATH=/config/config.yaml

  db:
    image: postgres:15
    container_name: go_gin_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gin_learn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: go_gin_adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  pgdata:
